export default {
    expo: {
      name: 'delatte-mobile',
      slug: 'delatte-mobile',
      extra: {
        EXPO_PUBLIC_API_URL: process.env.EXPO_PUBLIC_API_URL,
        EXPO_PUBLIC_AUTH0_DOMAIN: process.env.EXPO_PUBLIC_AUTH0_DOMAIN,
        EXPO_PUBLIC_AUTH0_CLIENT_ID: process.env.EXPO_PUBLIC_AUTH0_CLIENT_ID,
        EXPO_PUBLIC_AUTH0_BACKEND_CLIENT_ID: process.env.EXPO_PUBLIC_AUTH0_BACKEND_CLIENT_ID,
        EXPO_PUBLIC_AUTH0_BACKEND_CLIENT_SECRET: process.env.EXPO_PUBLIC_AUTH0_BACKEND_CLIENT_SECRET,
        EXPO_PUBLIC_AUTH0_AUDIENCE: process.env.EXPO_PUBLIC_AUTH0_AUDIENCE,
        EXPO_PUBLIC_GOOGLE_MAPS_KEY: process.env.EXPO_PUBLIC_GOOGLE_MAPS_KEY,
        EXPO_PUBLIC_CLOUDINARY_CLOUD_NAME: process.env.EXPO_PUBLIC_CLOUDINARY_CLOUD_NAME,
        EXPO_PUBLIC_CLOUDINARY_UPLOAD_PRESET: process.env.EXPO_PUBLIC_CLOUDINARY_UPLOAD_PRESET,
        eas: {
          projectId: 'c7705c53-d3e0-4d4a-9fc5-67863529c818'
        }
      }
    }
  }
  